<?php

return [

    // user register
     
    'taskstatus' => [
        '1' => 'auth.taskstatus1',
        '2' => 'auth.taskstatus2',
        '3' => 'auth.taskstatus3',
        '4' => 'auth.taskstatus4',
        '10' => 'auth.taskstatus10',
        '12' => 'auth.taskstatus12',
        '13' => 'auth.taskstatus13',
    ],


    'taskstatus' => [
        '1' => 'auth.taskstatus1',
        '2' => 'auth.taskstatus2',
        '3' => 'auth.taskstatus3',
        '4' => 'auth.taskstatus4',
        '10' => 'auth.taskstatus10',
        '12' => 'auth.taskstatus12',
        '13' => 'auth.taskstatus13',
    ],

    'cstatus' => [
        '1' => 'auth.cstatus1',
        '2' => 'auth.cstatus2',
        '3' => 'auth.cstatus3',
    ],

    'classtime' => [
        '0' => 'auth.classtime',
        '1' => '08:00～08:25',
        '2' => '08:30～08:55',
        '3' => '09:00～09:25',
        '4' => '09:30～09:55',
        '5' => '10:00～10:25',
        '6' => '10:30～10:55',
        '7' => '11:00～11:25',
        '8' => '11:30～11:55',
        '9' => '12:00～12:25',
        '10' => '12:30～12:55',
        '11' => '13:00～13:25',
        '12' => '13:30～13:55',
        '13' => '14:00～14:25',
        '14' => '14:30～14:55',
        '15' => '15:00～15:25',
        '16' => '15:30～15:55',
        '17' => '16:00～16:25',
        '18' => '16:30～16:55',
        '19' => '17:00～17:25',
        '20' => '17:30～17:55',
        '21' => '18:00～18:25',
        '22' => '18:30～18:55',
        '23' => '19:00～19:25',
        '24' => '19:30～19:55',
        '25' => '20:00～20:25',
        '26' => '20:30～20:55',
        '27' => '21:00～21:25',
        '28' => '21:30～21:55',
        '29' => '22:00～22:25',
        '30' => '22:30～22:55',
        '31' => '23:00～23:25',
        '32' => '23:30～23:55',
    ],

    'purpose' => [
        '0' => 'auth.purpose0',
        '1' => 'auth.purpose1',
        '2' => 'auth.purpose2',
        '3' => 'auth.purpose3',
    ],

    'compindustry' => [
        '0' => 'auth.industry0',
		'1' => 'auth.industry1',
		'2' => 'auth.industry2',
		'3' => 'auth.industry3',
		'4' => 'auth.industry4',
		'5' => 'auth.industry5',
		'6' => 'auth.industry6',
		'7' => 'auth.industry7',
		'8' => 'auth.industry8',
		'9' => 'auth.industry9',
		'10' => 'auth.industry10',
		'11' => 'auth.industry11',
    ],

    'positions' => [
        '0' => 'auth.position0',
		'1' => 'auth.position1',
		'2' => 'auth.position2',
		'3' => 'auth.position3',
		'4' => 'auth.position4',
		'5' => 'auth.position5',
    ],

    // application register

    'deliveryperiod' => [
        '0' => 'auth.deliveryperiod0',
        '1' => 'auth.deliveryperiod1',
        '2' => 'auth.deliveryperiod2',
        '3' => 'auth.deliveryperiod3',
        '4' => 'auth.deliveryperiod4',
    ],

    'contactmethod' => [
        '0' => 'auth.contactmethod0',
        '1' => 'auth.contactmethod1',
        '2' => 'auth.contactmethod2',
        '3' => 'auth.contactmethod3',
    ],

    'budget' => [
        '0' => 'auth.budget0',
        '1' => 'auth.budget1',
        '2' => 'auth.budget2',
        '3' => 'auth.budget3',
        '4' => 'auth.budget4',
    ],

    'infcgender' => [
        '0' => 'auth.infcgender0',
        '1' => 'auth.infcgender1',
        '2' => 'auth.infcgender2',
        // '3' => '指定なし',
    ],

    'infccountry' => [
        '0' => 'auth.infccountry0',
        '1' => 'auth.infccountry1',
        '2' => 'auth.infccountry2',
        '3' => 'auth.infccountry3',
    ],

    'infcgendertask' => [
        '0' => 'auth.infcgendertask0',
        '1' => 'auth.infcgendertask1',
        '2' => 'auth.infcgendertask2',
        '3' => 'auth.infcgendertask3',
    ],

    'infcmedia' => [
        '0' => 'auth.infcmedia0',
        '1' => 'auth.infcmedia1',
        '2' => 'auth.infcmedia2',
        '3' => 'auth.infcmedia3',
        '4' => 'auth.infcmedia4',
        '5' => 'auth.infcmedia5',
        '6' => 'auth.infcmedia6',
        '7' => 'auth.infcmedia7',
    ],

    'infcgenre' => [
        '0' => 'auth.infcgenre0',
        '1' => 'auth.infcgenre1',
        '2' => 'auth.infcgenre2',
        '3' => 'auth.infcgenre3',
        '4' => 'auth.infcgenre4',
        '5' => 'auth.infcgenre5',
        '6' => 'auth.infcgenre6',
        '7' => 'auth.infcgenre7',
        '8' => 'auth.infcgenre8',
        '9' => 'auth.infcgenre9',
        '10' => 'auth.infcgenre10',
    ],

    'gender' => [
        '0' => 'auth.gender0',
        '1' => 'auth.gender1',
        '2' => 'auth.gender2',
    ],

    'agerange' => [
        '0' => 'auth.agerange0',
        '1' => 'auth.agerange1',
        '2' => 'auth.agerange2',
        '3' => 'auth.agerange3',
        '4' => 'auth.agerange4',
        '5' => 'auth.agerange5',
        '6' => 'auth.agerange6',
    ],

    'city' => [
        '0' => 'auth.city0',
        '1' => '北海道',
        '2' => '青森県',
        '3' => '岩手県',
        '4' => '宮城県',
        '5' => '秋田県',
        '6' => '山形県',
        '7' => '福島県',
        '8' => '茨城県',
        '9' => '栃木県',
        '10' => '群馬県',
        '11' => '埼玉県',
        '12' => '千葉県',
        '13' => '東京都',
        '14' => '神奈川県',
        '15' => '新潟県',
        '16' => '富山県',
        '17' => '石川県',
        '18' => '福井県',
        '19' => '山梨県',
        '20' => '長野県',
        '21' => '岐阜県',
        '22' => '静岡県',
        '23' => '愛知県',
        '24' => '三重県',
        '25' => '滋賀県',
        '26' => '京都府',
        '27' => '大阪府',
        '28' => '兵庫県',
        '29' => '奈良県',
        '30' => '和歌山県',
        '31' => '鳥取県',
        '32' => '島根県',
        '33' => '岡山県',
        '34' => '広島県',
        '35' => '山口県',
        '36' => '徳島県',
        '37' => '香川県',
        '38' => '愛媛県',
        '39' => '高知県',
        '40' => '福岡県',
        '41' => '佐賀県',
        '42' => '長崎県',
        '43' => '熊本県',
        '44' => '大分県',
        '45' => '宮崎県',
        '46' => '鹿児島県',
        '47' => '沖縄県',
        '48' => 'auth.city1',
    ],

    'infcdesirepay' => [
        '0' => 'auth.infcdesirepay0',
        '1' => 'auth.infcdesirepay1',
        '2' => 'auth.infcdesirepay2',
        '3' => 'auth.infcdesirepay3',
        '4' => 'auth.infcdesirepay4',
        '5' => 'auth.infcdesirepay5',
    ],

    'inflstatus' => [
        '' => 'auth.inflstatus',
        '4' => 'auth.inflstatus4',
        '5' => 'auth.inflstatus5',
        '6' => 'auth.inflstatus6',
        '7' => 'auth.inflstatus7',
        '8' => 'auth.inflstatus8',
        '9' => 'auth.inflstatus9',
    ],

];
